[package]
name = "windows-service"
version = "0.2.0"
description = "A crate that provides facilities for management and implementation of windows services"
readme = "README.md"
authors = ["Mullvad VPN <admin@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>"]
keywords = ["windows", "service", "daemon"]
categories = ["api-bindings"]
repository = "https://github.com/mullvad/windows-service-rs"
license = "MIT/Apache-2.0"
edition = "2018"

[target.'cfg(windows)'.dependencies]
bitflags = "1.0.1"
err-derive = "0.1.5"
winapi = { git = "https://github.com/mullvad/winapi-rs.git", rev = "4bcf5cab87124bbeef8c1a445137494d874f8082", features = ["std", "winsvc", "winbase", "winerror"] }
widestring = "0.3.0"
